version: "3.9"
services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: "surf_it"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "<z5&+lLwlgB(]KV#"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/init_db:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d surf_it"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  app:
    build: .
    ports:
      - "8042:8042"
    depends_on:
      - postgres
